#
# Configuration file for mesosmock.
# Run mesosmock with the "-config" flag to specify a custom config.
#

# Listening address to bind on.
# Accepts both address:port or port number itself.
# listen_addr = "5050"
# listen_addr = "192.168.100.102:5050"
