#
# Configuration file for mesosmock.
# Run mesosmock with the "-config" flag to specify a custom config.
#

# IP address to listen on.
# ip = "127.0.0.1"

# Port to listen on.
# port = "5050"

# Hostname to use for the Mesos master.
# hostname = "localhost"

# Mesos mock cluster configuration.
# agent_count = 2
